# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import helloworld_pb2 as helloworld__pb2


class GerenciadorDeNotasStub(object):
    """interface de serviço
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarAlunos = channel.unary_unary(
                '/GerenciadorDeNotas/ListarAlunos',
                request_serializer=helloworld__pb2.ListarAlunosRequest.SerializeToString,
                response_deserializer=helloworld__pb2.ListarAlunosResponse.FromString,
                )


class GerenciadorDeNotasServicer(object):
    """interface de serviço
    """

    def ListarAlunos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GerenciadorDeNotasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarAlunos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarAlunos,
                    request_deserializer=helloworld__pb2.ListarAlunosRequest.FromString,
                    response_serializer=helloworld__pb2.ListarAlunosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GerenciadorDeNotas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GerenciadorDeNotas(object):
    """interface de serviço
    """

    @staticmethod
    def ListarAlunos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorDeNotas/ListarAlunos',
            helloworld__pb2.ListarAlunosRequest.SerializeToString,
            helloworld__pb2.ListarAlunosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
